{% set name = "pytextgrid" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytextgrid-{{ version }}.tar.gz
  sha256: 1b0794d55747ba6baf5bd5329403300b78dd91e53b170ddfdc0a1557f552c649

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pytextgrid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DavidDoukhan/pytextgrid
  summary: 'A toolbox for manipulating praat textgrid in python: creation, modification, analysis'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
